# Generated by Django 5.1.3 on 2024-11-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
